/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export type UserOperationStruct = {
  sender: PromiseOrValue<string>;
  nonce: PromiseOrValue<BigNumberish>;
  initCode: PromiseOrValue<BytesLike>;
  callData: PromiseOrValue<BytesLike>;
  callGasLimit: PromiseOrValue<BigNumberish>;
  verificationGasLimit: PromiseOrValue<BigNumberish>;
  preVerificationGas: PromiseOrValue<BigNumberish>;
  maxFeePerGas: PromiseOrValue<BigNumberish>;
  maxPriorityFeePerGas: PromiseOrValue<BigNumberish>;
  paymasterAndData: PromiseOrValue<BytesLike>;
  signature: PromiseOrValue<BytesLike>;
};

export type UserOperationStructOutput = [
  string,
  BigNumber,
  string,
  string,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  string,
  string
] & {
  sender: string;
  nonce: BigNumber;
  initCode: string;
  callData: string;
  callGasLimit: BigNumber;
  verificationGasLimit: BigNumber;
  preVerificationGas: BigNumber;
  maxFeePerGas: BigNumber;
  maxPriorityFeePerGas: BigNumber;
  paymasterAndData: string;
  signature: string;
};

export interface BLSSignatureAggregatorInterface extends utils.Interface {
  functions: {
    "BLS_DOMAIN()": FunctionFragment;
    "N()": FunctionFragment;
    "aggregateSignatures(bytes[])": FunctionFragment;
    "getRequestId((address,uint256,bytes,bytes,uint256,uint256,uint256,uint256,uint256,bytes,bytes))": FunctionFragment;
    "userOpToMessage((address,uint256,bytes,bytes,uint256,uint256,uint256,uint256,uint256,bytes,bytes))": FunctionFragment;
    "validateSignatures((address,uint256,bytes,bytes,uint256,uint256,uint256,uint256,uint256,bytes,bytes)[],bytes)": FunctionFragment;
    "validateUserOpSignature((address,uint256,bytes,bytes,uint256,uint256,uint256,uint256,uint256,bytes,bytes),bool)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "BLS_DOMAIN"
      | "N"
      | "aggregateSignatures"
      | "getRequestId"
      | "userOpToMessage"
      | "validateSignatures"
      | "validateUserOpSignature"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "BLS_DOMAIN",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "N", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "aggregateSignatures",
    values: [PromiseOrValue<BytesLike>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getRequestId",
    values: [UserOperationStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "userOpToMessage",
    values: [UserOperationStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "validateSignatures",
    values: [UserOperationStruct[], PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "validateUserOpSignature",
    values: [UserOperationStruct, PromiseOrValue<boolean>]
  ): string;

  decodeFunctionResult(functionFragment: "BLS_DOMAIN", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "N", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "aggregateSignatures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRequestId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userOpToMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateSignatures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateUserOpSignature",
    data: BytesLike
  ): Result;

  events: {};
}

export interface BLSSignatureAggregator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BLSSignatureAggregatorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    BLS_DOMAIN(overrides?: CallOverrides): Promise<[string]>;

    N(overrides?: CallOverrides): Promise<[BigNumber]>;

    aggregateSignatures(
      sigsForAggregation: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<[string] & { aggregatesSignature: string }>;

    getRequestId(
      userOp: UserOperationStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;

    userOpToMessage(
      userOp: UserOperationStruct,
      overrides?: CallOverrides
    ): Promise<[[BigNumber, BigNumber]]>;

    validateSignatures(
      userOps: UserOperationStruct[],
      signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    validateUserOpSignature(
      userOp: UserOperationStruct,
      offChainSigCheck: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string] & {
        sigForUserOp: string;
        sigForAggregation: string;
        offChainSigInfo: string;
      }
    >;
  };

  BLS_DOMAIN(overrides?: CallOverrides): Promise<string>;

  N(overrides?: CallOverrides): Promise<BigNumber>;

  aggregateSignatures(
    sigsForAggregation: PromiseOrValue<BytesLike>[],
    overrides?: CallOverrides
  ): Promise<string>;

  getRequestId(
    userOp: UserOperationStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  userOpToMessage(
    userOp: UserOperationStruct,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  validateSignatures(
    userOps: UserOperationStruct[],
    signature: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<void>;

  validateUserOpSignature(
    userOp: UserOperationStruct,
    offChainSigCheck: PromiseOrValue<boolean>,
    overrides?: CallOverrides
  ): Promise<
    [string, string, string] & {
      sigForUserOp: string;
      sigForAggregation: string;
      offChainSigInfo: string;
    }
  >;

  callStatic: {
    BLS_DOMAIN(overrides?: CallOverrides): Promise<string>;

    N(overrides?: CallOverrides): Promise<BigNumber>;

    aggregateSignatures(
      sigsForAggregation: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<string>;

    getRequestId(
      userOp: UserOperationStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    userOpToMessage(
      userOp: UserOperationStruct,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    validateSignatures(
      userOps: UserOperationStruct[],
      signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    validateUserOpSignature(
      userOp: UserOperationStruct,
      offChainSigCheck: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string] & {
        sigForUserOp: string;
        sigForAggregation: string;
        offChainSigInfo: string;
      }
    >;
  };

  filters: {};

  estimateGas: {
    BLS_DOMAIN(overrides?: CallOverrides): Promise<BigNumber>;

    N(overrides?: CallOverrides): Promise<BigNumber>;

    aggregateSignatures(
      sigsForAggregation: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRequestId(
      userOp: UserOperationStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userOpToMessage(
      userOp: UserOperationStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    validateSignatures(
      userOps: UserOperationStruct[],
      signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    validateUserOpSignature(
      userOp: UserOperationStruct,
      offChainSigCheck: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    BLS_DOMAIN(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    N(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    aggregateSignatures(
      sigsForAggregation: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRequestId(
      userOp: UserOperationStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    userOpToMessage(
      userOp: UserOperationStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    validateSignatures(
      userOps: UserOperationStruct[],
      signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    validateUserOpSignature(
      userOp: UserOperationStruct,
      offChainSigCheck: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
