/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as blsWalletSol from "./BLSWallet.sol";
export type { blsWalletSol };
import type * as lib from "./lib";
export type { lib };
export type { BLSSignatureAggregator } from "./BLSSignatureAggregator";
export type { IBLSWallet } from "./IBLSWallet";
