/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface UpgradeableOpenfortFactoryInterface extends utils.Interface {
  functions: {
    "accountImplementation()": FunctionFragment;
    "createAccountWithNonce(address,bytes32)": FunctionFragment;
    "entrypointContract()": FunctionFragment;
    "getAddressWithNonce(address,bytes32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "accountImplementation"
      | "createAccountWithNonce"
      | "entrypointContract"
      | "getAddressWithNonce"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "accountImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createAccountWithNonce",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "entrypointContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAddressWithNonce",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;

  decodeFunctionResult(
    functionFragment: "accountImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAccountWithNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "entrypointContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAddressWithNonce",
    data: BytesLike
  ): Result;

  events: {
    "AccountCreated(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AccountCreated"): EventFragment;
}

export interface AccountCreatedEventObject {
  account: string;
  accountAdmin: string;
}
export type AccountCreatedEvent = TypedEvent<
  [string, string],
  AccountCreatedEventObject
>;

export type AccountCreatedEventFilter = TypedEventFilter<AccountCreatedEvent>;

export interface UpgradeableOpenfortFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: UpgradeableOpenfortFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    accountImplementation(overrides?: CallOverrides): Promise<[string]>;

    createAccountWithNonce(
      _admin: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    entrypointContract(overrides?: CallOverrides): Promise<[string]>;

    getAddressWithNonce(
      _admin: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  accountImplementation(overrides?: CallOverrides): Promise<string>;

  createAccountWithNonce(
    _admin: PromiseOrValue<string>,
    _nonce: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  entrypointContract(overrides?: CallOverrides): Promise<string>;

  getAddressWithNonce(
    _admin: PromiseOrValue<string>,
    _nonce: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    accountImplementation(overrides?: CallOverrides): Promise<string>;

    createAccountWithNonce(
      _admin: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    entrypointContract(overrides?: CallOverrides): Promise<string>;

    getAddressWithNonce(
      _admin: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "AccountCreated(address,address)"(
      account?: PromiseOrValue<string> | null,
      accountAdmin?: PromiseOrValue<string> | null
    ): AccountCreatedEventFilter;
    AccountCreated(
      account?: PromiseOrValue<string> | null,
      accountAdmin?: PromiseOrValue<string> | null
    ): AccountCreatedEventFilter;
  };

  estimateGas: {
    accountImplementation(overrides?: CallOverrides): Promise<BigNumber>;

    createAccountWithNonce(
      _admin: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    entrypointContract(overrides?: CallOverrides): Promise<BigNumber>;

    getAddressWithNonce(
      _admin: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    accountImplementation(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createAccountWithNonce(
      _admin: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    entrypointContract(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAddressWithNonce(
      _admin: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
